apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: longhorn-ui
  namespace: infra-system
spec:
  entryPoints:
    - websecure # HTTPS
  routes:
    - match: Host(`longhorn.stc.local`)
      kind: Rule
      services:
        - name: longhorn-frontend
          port: 80
  tls:
    secretName: longhorn-tls