apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-server
  namespace: infra-system
spec:
  entryPoints:
    - websecure # HTTPS
  routes:
    - match: Host(`argocd.stc.local`)
      kind: Rule
      services:
        - name: infra-core-argocd-server # K8s d'ArgoCD
          port: 80
  tls:
    secretName: argocd-tls
