apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-config
  namespace: infra-system
spec:
  project: default
  source:
    repoURL: https://github.com/jorisvilardell/my-talos-cluster
    targetRevision: main
    path: cluster-config
    plugin:
      name: avp-sops
  destination:
    server: https://kubernetes.default.svc
    namespace: infra-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
