apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - argocd/certificate.yaml
  - argocd/ingressroute.yaml
  - longhorn/certificate.yaml
  - longhorn/ingressroute.yaml
  - longhorn/namespace.yaml
  - pki/issuer.yaml
generators:
  - secret-generator.yaml
